adding unit test coverage check

diff --git a/.github/workflows/go-build-workflow.yaml b/.github/workflows/go-build-workflow.yaml
--- a/.github/workflows/go-build-workflow.yaml
+++ b/.github/workflows/go-build-workflow.yaml
@@ -42,8 +42,36 @@ jobs:
         name: Unit-Test-Results
         path: TestResults.json
 
-  codestandards:
-    name: Code Standards
+  unittestcoverage:
+    name: Unit Test Coverage
+    runs-on: ubuntu-latest
+    needs: unittest
+    env:
+        TESTCOVERAGE_THRESHOLD: 90
+    steps:
+    - uses: actions/checkout@v3
+
+    - name: Set up Go
+      uses: actions/setup-go@v3
+      with:
+        go-version: 1.19
+        
+    - name: check
+      run: |
+            echo "Quality Gate: checking test coverage is above threshold ..."
+            echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
+            totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
+            echo "Current test coverage : $totalCoverage %"
+            if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
+                echo "OK"
+            else
+                echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
+                echo "Failed"
+                exit 1
+            fi
+
+  dependencyVulnterabilityCheck:
+    name: Dependency Vulnerability Check
     runs-on: ubuntu-latest
     needs: unittest
     steps:
